language: go
sudo: false
go:
  - 1.2

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash -c "$(git log -1 --pretty=%B | tail -2 | head -1)"
